### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by philher** [AnubisNekhet/AnuPpuccin#111]
**Describe the bug**
Custom checkbox styling is applied to checked subtasks in reading mode.

**To Reproduce**
In a note, use the snippet below and toggle between live preview and reading mode.
```md
- [>] Task 1
	- [x] Subtask 1 ✅ 2023-03-08
	- [ ] Subtask 2
	- [x] Subtask 3 ✅ 2023-03-08
		- [ ] Subsubtask1
		- [x] Subsubtask2 ✅ 2023-03-08
	- [-] Subtask 3
		- [ ] Subsubtask1
		- [x] Subsubtask2 ✅ 2023-03-08
- [x] Task 2
```

**Expected behavior**
Reading mode styling should remain similar to live preview

**Screenshots**
+ Live Preview:
  ![image](https://user-images.githubusercontent.com/31505982/223752686-cfa93e01-153e-4db7-a1ae-fb9e5dc51799.png)
+ Reading mode
  ![image](https://user-images.githubusercontent.com/31505982/223752547-f58ea23d-505b-4a92-a7d1-4c957701beaa.png)

**Additional context**
Obsidian 1.1.16 on Ubuntu 20.04 LTS

I am not 100% sure that the theme's CSS is the issue, my knowledge of CSS is rather basic, therefore do not hesitate to close the issue if so.

**Comment by AnubisNekhet** [comment]
Fixed with the latest commit

**Comment by leelhn2345** [comment]
It seems that there is a new bug. 

Live preview: 
![image](https://user-images.githubusercontent.com/64735315/224962167-dda5c90d-ae0b-4005-86d9-f11d63a062aa.png)

Reading mode: 
![image](https://user-images.githubusercontent.com/64735315/224962310-6cafe7d0-44a2-40ac-8c0e-87fe967d7177.png)

**Comment by AnubisNekhet** [comment]
I can't seem to reproduce your issue. Does it still persist with all snippets disabled?

**Comment by leelhn2345** [comment]
> I can't seem to reproduce your issue. Does it still persist with all snippets disabled?

yup the problem still persists. 
and I have tried reproducing this error in another vault, and neither can I reproduce it as well 😅.

sorry for the inconvenience.

**Comment by leelhn2345** [comment]
Ok I've found the error. It is due to this empty line over here.

![image](https://user-images.githubusercontent.com/64735315/225043375-f8fbf9fc-9894-4351-9e29-620a0177db79.png)
